.PHONY: install clean

ITERM2_PLIST := ~/Library/Preferences/com.googlecode.iterm2.plist

iterm2-install:
	ln -sf $(abspath com.googlecode.iterm2.plist) $(ITERM2_PLIST)

iterm2-clean:
	rm -f $(ITERM2_PLIST)
